services:

  mysqldb:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: autoloc
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root

  autoloc:
    image: rayanehr/projet_pp_location_vehicules-backend:latest
    container_name: spring_boot_app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/autoloc?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test

  autoloc-front:
    image: rayanehr/projet_pp_location_vehicules-frontend:latest
    container_name: angular_app
    ports:
      - "80:80"
    depends_on:
      - autoloc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: test
      PMA_PASSWORD: test